name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou master selon ton cas

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 123.123.123.123 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        rsync -avz --delete ./ root@123.123.123.123:/var/www/bertadrien.fr/
